#! /bin/bash

# NAME:    rofi-menu-history
# PURPOSE: Implements a rofi mode which lists files which have been accessed before 
#          and opens an appropriate application upon selection.
# EXAMPLE: rofi -show history -modi history:rofi-menu-history

delimiter="|"

if [ "$@" ]
then
    ftype=$(echo -n "$@"|cut -d $delimiter -f 1)
    path=$(echo -n "$@"|cut -d $delimiter -f 2)

    # Wizardry to resolve path (~, $HOME, etc) and handle file names with spaces
    path=$(sh -c "echo -n $path")
    escaped_path=$(sh -c "echo -n $path"|sed -e 's/ /\\ /g')

    case "$ftype" in
        txt)
             exec termite -e "vim $escaped_path" >/dev/null ;;
        pdf)
             exec zathura "$path" >/dev/null ;;
        vlc)
             exec vlc $escaped_path >/dev/null ;;
        osp)
             exec openshot-qt $escaped_path >/dev/null ;;
    esac

    exit;
else
    # VIM history
    grep '^>' $HOME/.viminfo|sed -e 's/^>/txt|/' -e '/tmp/ d' -e '/COMMIT_EDITMSG/ d' -e '/MERGE_MSG/ d'

    # zathura history
    sed -n -e '/^\[.*\]/p' $HOME/.local/share/zathura/history|sed -e 's/\[/pdf|/g' -e 's/\]//g'

    # VLC recent files list is in the config file $HOME/.config/vlc/vlc-qt-interface.conf under the section: RecentsMRL
    sed -n '/\[RecentsMRL\]/,+1p' $HOME/.config/vlc/vlc-qt-interface.conf |tail -n 1|sed 's/list=/ /'|tr "," "\n"|sed -e 's/^ /vlc|/'

    # OpenShot
    jq 'map(select(.setting == "recent_projects"))|.[0].value' ~/.openshot_qt/openshot.settings|tail -n +2|head -n -1|sed -e 's/^  \"/osp|/' -e 's/\",$//' -e 's/\"$//'
fi
