#! /bin/bash

# NAME:    rofi-menu-open
# PURPOSE: Implements a rofi mode which lists files in the user's home directory and opens an appropriate application upon selection.
# EXAMPLE: rofi -show open -modi open:rofi-menu-open

if [ "$@" ]
then
    path="$@"
    fext="${path##*.}"
    escaped_path=$(sh -c "echo -n $path"|sed -e 's/ /\\ /g')

    case "$fext" in
        osp)
            exec openshot-qt $escaped_path >/dev/null ;;
          *)
            mimetype=$(file --mime-type -b "$path")
            ftype=$(echo $mimetype | cut -d "/" -f 1)

            case "$ftype" in
                text)
                    exec alacritty -e vim "$path" >/dev/null ;;
                image)
                    exec sxiv "$path" >/dev/null ;;
                video | audio)
                    exec vlc "$path" >/dev/null ;;
                application)
                    fformat=$(echo $mimetype | cut -d "/" -f 2)

                    case "$fformat" in
                        pdf) 
                            exec zathura "$path" >/dev/null ;;
                        *)
                            exec xdg-open "$escaped_path" ;;
                    esac ;;
            esac ;;
    esac

    exit;
else
    fd -t f -H -E .git -E .svn -E .hg . $HOME
fi
