#! /bin/bash

# NAME:    rofi-menu-shutdown
# PURPOSE: Implements a rofi mode which lists the options to either log out of the Xsession (BSPWM window manager), Hyprland session, shut down, or reboot.
# EXAMPLE: rofi -show shutdown -modi shutdown:rofi-menu-shutdown

if [ "$@" ]
then
    case "$@" in
        logout)
             if [ -z "$WAYLAND_DISPLAY" ]
             then
                exec hyprctl dispatch exit
             else
                 exec bspc quit
             fi ;;
        shutdown)
             exec shutdown -P now ;;
        reboot)
             exec shutdown -r now ;;
    esac

    exit;
else
    echo logout
    echo shutdown
    echo reboot
fi
